import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('pt');
  const [showOptions, setShowOptions] = useState(false);

  const languages = {
    pt: {
      language: 'Português',
      icon: '🇧🇷'
    },
    en: {
      language: 'English',
      icon: '🇺🇸'
    },
    es: {
      language: 'Español',
      icon: '🇪🇸'
    },
    fr: {
      language: 'Français',
      icon: '🇫🇷'
    },
    de: {
      language: 'Deutsch',
      icon: '🇩🇪'
    },
    it: {
      language: 'Italiano',
      icon: '🇮🇹'
    },
    ja: {
      language: '日本語',
      icon: '🇯🇵'
    },
    zh: {
      language: '中文',
      icon: '🇨🇳'
    },
    ru: {
      language: 'Русский',
      icon: '🇷🇺'
    },
    ar: {
      language: 'العربية',
      icon: '🇸🇦'
    },
    hi: {
      language: 'हिन्दी',
      icon: '🇮🇳'
    },
    ko: {
      language: '한국어',
      icon: '🇰🇷'
    }
  };

  const translations = {
    pt: {
      title: 'EchoTap',
      bio: 'Soluções digitais inovadoras para seu negócio',
      website: 'Website',
      websiteDesc: 'Acesse o site',
      instagram: 'Instagram',
      instagramDesc: 'Siga no Instagram',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'Entre em contato',
      linkedin: 'LinkedIn',
      linkedinDesc: 'Acesse o LinkedIn',
      google: 'Google',
      googleDesc: 'Avalie no Google',
      github: 'GitHub',
      githubDesc: 'Acesse o GitHub',
      youtube: 'YouTube',
      youtubeDesc: 'Acesse o YouTube',
      facebook: 'Facebook',
      facebookDesc: 'Acesse o Facebook',
      tiktok: 'TikTok',
      tiktokDesc: 'Acesse o TikTok',
      twitter: 'Twitter',
      twitterDesc: 'Acesse o Twitter',
      behance: 'Behance',
      behanceDesc: 'Acesse o Behance',
      medium: 'Medium',
      mediumDesc: 'Acesse o Medium',
      telegram: 'Telegram',
      telegramDesc: 'Acesse o Telegram',
      discord: 'Discord',
      discordDesc: 'Acesse o Discord',
      email: 'Email',
      emailDesc: 'Envie um email',
      calendly: 'Calendly',
      calendlyDesc: 'Agende uma reunião',
      spotify: 'Spotify',
      spotifyDesc: 'Acesse o Spotify',
      pinterest: 'Pinterest',
      pinterestDesc: 'Acesse o Pinterest',
      reddit: 'Reddit',
      redditDesc: 'Acesse o Reddit',
      twitch: 'Twitch',
      twitchDesc: 'Acesse a Twitch',
      language: 'Idioma',
      footer: 'Desenvolvido com',
      by: 'por'
    },
    en: {
      title: 'EchoTap',
      bio: 'Innovative digital solutions for your business',
      website: 'Website',
      websiteDesc: 'Visit the website',
      instagram: 'Instagram',
      instagramDesc: 'Follow on Instagram',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'Get in touch',
      linkedin: 'LinkedIn',
      linkedinDesc: 'Visit the LinkedIn',
      google: 'Google',
      googleDesc: 'Rate on Google',
      github: 'GitHub',
      githubDesc: 'Visit the GitHub',
      youtube: 'YouTube',
      youtubeDesc: 'Visit the YouTube',
      facebook: 'Facebook',
      facebookDesc: 'Visit the Facebook',
      tiktok: 'TikTok',
      tiktokDesc: 'Visit the TikTok',
      twitter: 'Twitter',
      twitterDesc: 'Visit the Twitter',
      behance: 'Behance',
      behanceDesc: 'Visit the Behance',
      medium: 'Medium',
      mediumDesc: 'Visit the Medium',
      telegram: 'Telegram',
      telegramDesc: 'Visit the Telegram',
      discord: 'Discord',
      discordDesc: 'Visit the Discord',
      email: 'Email',
      emailDesc: 'Send an email',
      calendly: 'Calendly',
      calendlyDesc: 'Schedule a meeting',
      spotify: 'Spotify',
      spotifyDesc: 'Visit the Spotify',
      pinterest: 'Pinterest',
      pinterestDesc: 'Visit the Pinterest',
      reddit: 'Reddit',
      redditDesc: 'Visit the Reddit',
      twitch: 'Twitch',
      twitchDesc: 'Visit the Twitch',
      language: 'Language',
      footer: 'Developed with',
      by: 'by'
    },
    es: {
      title: 'EchoTap',
      bio: 'Soluciones digitales innovadoras para tu negocio',
      website: 'Sitio Web',
      websiteDesc: 'Visita el sitio',
      instagram: 'Instagram',
      instagramDesc: 'Sigue en Instagram',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'Contacta',
      linkedin: 'LinkedIn',
      linkedinDesc: 'Visita el LinkedIn',
      google: 'Google',
      googleDesc: 'Califica en Google',
      github: 'GitHub',
      githubDesc: 'Visita el GitHub',
      youtube: 'YouTube',
      youtubeDesc: 'Visita el YouTube',
      facebook: 'Facebook',
      facebookDesc: 'Visita el Facebook',
      tiktok: 'TikTok',
      tiktokDesc: 'Visita el TikTok',
      twitter: 'Twitter',
      twitterDesc: 'Visita el Twitter',
      behance: 'Behance',
      behanceDesc: 'Visita el Behance',
      medium: 'Medium',
      mediumDesc: 'Visita el Medium',
      telegram: 'Telegram',
      telegramDesc: 'Visita el Telegram',
      discord: 'Discord',
      discordDesc: 'Visita el Discord',
      email: 'Email',
      emailDesc: 'Envía un email',
      calendly: 'Calendly',
      calendlyDesc: 'Agenda una reunión',
      spotify: 'Spotify',
      spotifyDesc: 'Visita el Spotify',
      pinterest: 'Pinterest',
      pinterestDesc: 'Visita el Pinterest',
      reddit: 'Reddit',
      redditDesc: 'Visita el Reddit',
      twitch: 'Twitch',
      twitchDesc: 'Visita la Twitch',
      language: 'Idioma',
      footer: 'Desarrollado con',
      by: 'por'
    },
    fr: {
      title: 'EchoTap',
      bio: 'Solutions numériques innovantes pour votre entreprise',
      website: 'Site Web',
      websiteDesc: 'Visitez le site',
      instagram: 'Instagram',
      instagramDesc: 'Suivez sur Instagram',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'Contactez',
      linkedin: 'LinkedIn',
      linkedinDesc: 'Visitez le LinkedIn',
      google: 'Google',
      googleDesc: 'Évaluez sur Google',
      github: 'GitHub',
      githubDesc: 'Visitez le GitHub',
      youtube: 'YouTube',
      youtubeDesc: 'Visitez le YouTube',
      facebook: 'Facebook',
      facebookDesc: 'Visitez le Facebook',
      tiktok: 'TikTok',
      tiktokDesc: 'Visitez le TikTok',
      twitter: 'Twitter',
      twitterDesc: 'Visitez le Twitter',
      behance: 'Behance',
      behanceDesc: 'Visitez le Behance',
      medium: 'Medium',
      mediumDesc: 'Visitez le Medium',
      telegram: 'Telegram',
      telegramDesc: 'Visitez le Telegram',
      discord: 'Discord',
      discordDesc: 'Visitez le Discord',
      email: 'Email',
      emailDesc: 'Envoyez un email',
      calendly: 'Calendly',
      calendlyDesc: 'Planifiez une réunion',
      spotify: 'Spotify',
      spotifyDesc: 'Visitez le Spotify',
      pinterest: 'Pinterest',
      pinterestDesc: 'Visitez le Pinterest',
      reddit: 'Reddit',
      redditDesc: 'Visitez le Reddit',
      twitch: 'Twitch',
      twitchDesc: 'Visitez la Twitch',
      language: 'Langue',
      footer: 'Développé avec',
      by: 'par'
    },
    de: {
      title: 'EchoTap',
      bio: 'Innovative digitale Lösungen für Ihr Unternehmen',
      website: 'Webseite',
      websiteDesc: 'Besuchen Sie die Website',
      instagram: 'Instagram',
      instagramDesc: 'Folgen Sie auf Instagram',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'Kontaktieren',
      linkedin: 'LinkedIn',
      linkedinDesc: 'Besuchen Sie das LinkedIn',
      google: 'Google',
      googleDesc: 'Bewerten Sie auf Google',
      github: 'GitHub',
      githubDesc: 'Besuchen Sie das GitHub',
      youtube: 'YouTube',
      youtubeDesc: 'Besuchen Sie das YouTube',
      facebook: 'Facebook',
      facebookDesc: 'Besuchen Sie das Facebook',
      tiktok: 'TikTok',
      tiktokDesc: 'Besuchen Sie das TikTok',
      twitter: 'Twitter',
      twitterDesc: 'Besuchen Sie das Twitter',
      behance: 'Behance',
      behanceDesc: 'Besuchen Sie das Behance',
      medium: 'Medium',
      mediumDesc: 'Besuchen Sie das Medium',
      telegram: 'Telegram',
      telegramDesc: 'Besuchen Sie das Telegram',
      discord: 'Discord',
      discordDesc: 'Besuchen Sie das Discord',
      email: 'Email',
      emailDesc: 'Senden Sie eine E-Mail',
      calendly: 'Calendly',
      calendlyDesc: 'Vereinbaren Sie ein Meeting',
      spotify: 'Spotify',
      spotifyDesc: 'Besuchen Sie das Spotify',
      pinterest: 'Pinterest',
      pinterestDesc: 'Besuchen Sie das Pinterest',
      reddit: 'Reddit',
      redditDesc: 'Besuchen Sie das Reddit',
      twitch: 'Twitch',
      twitchDesc: 'Besuchen Sie die Twitch',
      language: 'Sprache',
      footer: 'Entwickelt mit',
      by: 'von'
    },
    it: {
      title: 'EchoTap',
      bio: 'Soluzioni digitali innovative per la tua azienda',
      website: 'Sito Web',
      websiteDesc: 'Visita il sito',
      instagram: 'Instagram',
      instagramDesc: 'Segui su Instagram',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'Contatta',
      linkedin: 'LinkedIn',
      linkedinDesc: 'Visita il LinkedIn',
      google: 'Google',
      googleDesc: 'Valuta su Google',
      github: 'GitHub',
      githubDesc: 'Visita il GitHub',
      youtube: 'YouTube',
      youtubeDesc: 'Visita il YouTube',
      facebook: 'Facebook',
      facebookDesc: 'Visita il Facebook',
      tiktok: 'TikTok',
      tiktokDesc: 'Visita il TikTok',
      twitter: 'Twitter',
      twitterDesc: 'Visita il Twitter',
      behance: 'Behance',
      behanceDesc: 'Visita il Behance',
      medium: 'Medium',
      mediumDesc: 'Visita il Medium',
      telegram: 'Telegram',
      telegramDesc: 'Visita il Telegram',
      discord: 'Discord',
      discordDesc: 'Visita il Discord',
      email: 'Email',
      emailDesc: 'Invia una email',
      calendly: 'Calendly',
      calendlyDesc: 'Prenota una riunione',
      spotify: 'Spotify',
      spotifyDesc: 'Visita lo Spotify',
      pinterest: 'Pinterest',
      pinterestDesc: 'Visita il Pinterest',
      reddit: 'Reddit',
      redditDesc: 'Visita il Reddit',
      twitch: 'Twitch',
      twitchDesc: 'Visita la Twitch',
      language: 'Lingua',
      footer: 'Sviluppato con',
      by: 'da'
    },
    ja: {
      title: 'EchoTap',
      bio: 'ビジネスのための革新的なデジタルソリューション',
      website: 'ウェブサイト',
      websiteDesc: 'サイトを訪問',
      instagram: 'Instagram',
      instagramDesc: 'Instagramでフォロー',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'お問い合わせ',
      linkedin: 'LinkedIn',
      linkedinDesc: 'LinkedInを訪問',
      google: 'Google',
      googleDesc: 'Googleで評価',
      github: 'GitHub',
      githubDesc: 'GitHubを訪問',
      youtube: 'YouTube',
      youtubeDesc: 'YouTubeを訪問',
      facebook: 'Facebook',
      facebookDesc: 'Facebookを訪問',
      tiktok: 'TikTok',
      tiktokDesc: 'TikTokを訪問',
      twitter: 'Twitter',
      twitterDesc: 'Twitterを訪問',
      behance: 'Behance',
      behanceDesc: 'Behanceを訪問',
      medium: 'Medium',
      mediumDesc: 'Mediumを訪問',
      telegram: 'Telegram',
      telegramDesc: 'Telegramを訪問',
      discord: 'Discord',
      discordDesc: 'Discordを訪問',
      email: 'Email',
      emailDesc: 'メールを送信',
      calendly: 'Calendly',
      calendlyDesc: 'ミーティングを予約',
      spotify: 'Spotify',
      spotifyDesc: 'Spotifyを訪問',
      pinterest: 'Pinterest',
      pinterestDesc: 'Pinterestを訪問',
      reddit: 'Reddit',
      redditDesc: 'Redditを訪問',
      twitch: 'Twitch',
      twitchDesc: 'Twitchを訪問',
      language: '言語',
      footer: '開発者',
      by: 'by'
    },
    zh: {
      title: 'EchoTap',
      bio: '为您的企业提供创新的数字解决方案',
      website: '网站',
      websiteDesc: '访问网站',
      instagram: 'Instagram',
      instagramDesc: '在Instagram上关注',
      whatsapp: 'WhatsApp',
      whatsappDesc: '联系',
      linkedin: 'LinkedIn',
      linkedinDesc: '访问LinkedIn',
      google: 'Google',
      googleDesc: '在Google上评价',
      github: 'GitHub',
      githubDesc: '访问GitHub',
      youtube: 'YouTube',
      youtubeDesc: '访问YouTube',
      facebook: 'Facebook',
      facebookDesc: '访问Facebook',
      tiktok: 'TikTok',
      tiktokDesc: '访问TikTok',
      twitter: 'Twitter',
      twitterDesc: '访问Twitter',
      behance: 'Behance',
      behanceDesc: '访问Behance',
      medium: 'Medium',
      mediumDesc: '访问Medium',
      telegram: 'Telegram',
      telegramDesc: '访问Telegram',
      discord: 'Discord',
      discordDesc: '访问Discord',
      email: 'Email',
      emailDesc: '发送邮件',
      calendly: 'Calendly',
      calendlyDesc: '安排会议',
      spotify: 'Spotify',
      spotifyDesc: '访问Spotify',
      pinterest: 'Pinterest',
      pinterestDesc: '访问Pinterest',
      reddit: 'Reddit',
      redditDesc: '访问Reddit',
      twitch: 'Twitch',
      twitchDesc: '访问Twitch',
      language: '语言',
      footer: '由',
      by: '开发'
    },
    ru: {
      title: 'EchoTap',
      bio: 'Инновационные цифровые решения для вашего бизнеса',
      website: 'Веб-сайт',
      websiteDesc: 'Посетите сайт',
      instagram: 'Instagram',
      instagramDesc: 'Подписывайтесь в Instagram',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'Связаться',
      linkedin: 'LinkedIn',
      linkedinDesc: 'Посетите LinkedIn',
      google: 'Google',
      googleDesc: 'Оцените на Google',
      github: 'GitHub',
      githubDesc: 'Посетите GitHub',
      youtube: 'YouTube',
      youtubeDesc: 'Посетите YouTube',
      facebook: 'Facebook',
      facebookDesc: 'Посетите Facebook',
      tiktok: 'TikTok',
      tiktokDesc: 'Посетите TikTok',
      twitter: 'Twitter',
      twitterDesc: 'Посетите Twitter',
      behance: 'Behance',
      behanceDesc: 'Посетите Behance',
      medium: 'Medium',
      mediumDesc: 'Посетите Medium',
      telegram: 'Telegram',
      telegramDesc: 'Посетите Telegram',
      discord: 'Discord',
      discordDesc: 'Посетите Discord',
      email: 'Email',
      emailDesc: 'Отправить письмо',
      calendly: 'Calendly',
      calendlyDesc: 'Запланировать встречу',
      spotify: 'Spotify',
      spotifyDesc: 'Посетите Spotify',
      pinterest: 'Pinterest',
      pinterestDesc: 'Посетите Pinterest',
      reddit: 'Reddit',
      redditDesc: 'Посетите Reddit',
      twitch: 'Twitch',
      twitchDesc: 'Посетите Twitch',
      language: 'Язык',
      footer: 'Разработано',
      by: 'от'
    },
    ar: {
      title: 'EchoTap',
      bio: 'حلول رقمية مبتكرة لعملك',
      website: 'الموقع الإلكتروني',
      websiteDesc: 'زيارة الموقع',
      instagram: 'Instagram',
      instagramDesc: 'تابع على Instagram',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'تواصل',
      linkedin: 'LinkedIn',
      linkedinDesc: 'زيارة LinkedIn',
      google: 'Google',
      googleDesc: 'قيم على Google',
      github: 'GitHub',
      githubDesc: 'زيارة GitHub',
      youtube: 'YouTube',
      youtubeDesc: 'زيارة YouTube',
      facebook: 'Facebook',
      facebookDesc: 'زيارة Facebook',
      tiktok: 'TikTok',
      tiktokDesc: 'زيارة TikTok',
      twitter: 'Twitter',
      twitterDesc: 'زيارة Twitter',
      behance: 'Behance',
      behanceDesc: 'زيارة Behance',
      medium: 'Medium',
      mediumDesc: 'زيارة Medium',
      telegram: 'Telegram',
      telegramDesc: 'زيارة Telegram',
      discord: 'Discord',
      discordDesc: 'زيارة Discord',
      email: 'Email',
      emailDesc: 'إرسال بريد إلكتروني',
      calendly: 'Calendly',
      calendlyDesc: 'جدولة اجتماع',
      spotify: 'Spotify',
      spotifyDesc: 'زيارة Spotify',
      pinterest: 'Pinterest',
      pinterestDesc: 'زيارة Pinterest',
      reddit: 'Reddit',
      redditDesc: 'زيارة Reddit',
      twitch: 'Twitch',
      twitchDesc: 'زيارة Twitch',
      language: 'اللغة',
      footer: 'تم التطوير بواسطة',
      by: 'من'
    },
    hi: {
      title: 'EchoTap',
      bio: 'आपके व्यवसाय के लिए नवीन डिजिटल समाधान',
      website: 'वेबसाइट',
      websiteDesc: 'वेबसाइट देखें',
      instagram: 'Instagram',
      instagramDesc: 'Instagram पर फॉलो करें',
      whatsapp: 'WhatsApp',
      whatsappDesc: 'संपर्क करें',
      linkedin: 'LinkedIn',
      linkedinDesc: 'LinkedIn देखें',
      google: 'Google',
      googleDesc: 'Google पर रेट करें',
      github: 'GitHub',
      githubDesc: 'GitHub देखें',
      youtube: 'YouTube',
      youtubeDesc: 'YouTube देखें',
      facebook: 'Facebook',
      facebookDesc: 'Facebook देखें',
      tiktok: 'TikTok',
      tiktokDesc: 'TikTok देखें',
      twitter: 'Twitter',
      twitterDesc: 'Twitter देखें',
      behance: 'Behance',
      behanceDesc: 'Behance देखें',
      medium: 'Medium',
      mediumDesc: 'Medium देखें',
      telegram: 'Telegram',
      telegramDesc: 'Telegram देखें',
      discord: 'Discord',
      discordDesc: 'Discord देखें',
      email: 'Email',
      emailDesc: 'ईमेल भेजें',
      calendly: 'Calendly',
      calendlyDesc: 'मीटिंग शेड्यूल करें',
      spotify: 'Spotify',
      spotifyDesc: 'Spotify देखें',
      pinterest: 'Pinterest',
      pinterestDesc: 'Pinterest देखें',
      reddit: 'Reddit',
      redditDesc: 'Reddit देखें',
      twitch: 'Twitch',
      twitchDesc: 'Twitch देखें',
      language: 'भाषा',
      footer: 'विकसित',
      by: 'द्वारा'
    },
    ko: {
      title: 'EchoTap',
      bio: '비즈니스를 위한 혁신적인 디지털 솔루션',
      website: '웹사이트',
      websiteDesc: '웹사이트 방문',
      instagram: 'Instagram',
      instagramDesc: 'Instagram에서 팔로우',
      whatsapp: 'WhatsApp',
      whatsappDesc: '연락하기',
      linkedin: 'LinkedIn',
      linkedinDesc: 'LinkedIn 방문',
      google: 'Google',
      googleDesc: 'Google에서 평가',
      github: 'GitHub',
      githubDesc: 'GitHub 방문',
      youtube: 'YouTube',
      youtubeDesc: 'YouTube 방문',
      facebook: 'Facebook',
      facebookDesc: 'Facebook 방문',
      tiktok: 'TikTok',
      tiktokDesc: 'TikTok 방문',
      twitter: 'Twitter',
      twitterDesc: 'Twitter 방문',
      behance: 'Behance',
      behanceDesc: 'Behance 방문',
      medium: 'Medium',
      mediumDesc: 'Medium 방문',
      telegram: 'Telegram',
      telegramDesc: 'Telegram 방문',
      discord: 'Discord',
      discordDesc: 'Discord 방문',
      email: 'Email',
      emailDesc: '이메일 보내기',
      calendly: 'Calendly',
      calendlyDesc: '미팅 예약',
      spotify: 'Spotify',
      spotifyDesc: 'Spotify 방문',
      pinterest: 'Pinterest',
      pinterestDesc: 'Pinterest 방문',
      reddit: 'Reddit',
      redditDesc: 'Reddit 방문',
      twitch: 'Twitch',
      twitchDesc: 'Twitch 방문',
      language: '언어',
      footer: '개발',
      by: 'by'
    }
  };

  const toggleLanguage = (lang) => {
    setCurrentLanguage(lang);
  };

  return (
    <LanguageContext.Provider value={{ 
      currentLanguage, 
      toggleLanguage, 
      translations: translations[currentLanguage],
      languages,
      showOptions,
      setShowOptions
    }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 